### ISSUE TITLE
typo missint double dash dest-port

### ISSUE THREAD

**Issue by ghost** [janeczku/Docker-RemoteSyslog2#1]
Hi

Missing a double dash in front of the dest-port and the SYSLOG_PORT will not be evaluated.

Thanks

**Comment by janeczku** [comment]
Thanks @alexaccedo. Fixed in https://github.com/janeczku/Docker-RemoteSyslog2/commit/8701e10e35c3da55f050d2d4d16fbfdd0e4a4ff0
